### ISSUE TITLE
GLOBALS["et_monarch"] is null

### ISSUE THREAD

**Issue by rejhgadellaa** [mmirus/monarch-sharing-shortcode#1] opened 2018-10-08 09:36 UTC
I'm getting the following error when trying to add the `[monarch_share]` shortcode to a sidebar widget.

```
PHP Fatal error:  Uncaught Error: Call to a member function get_icons_list() on null in /wp-content/plugins/monarch-sharing-shortcode-master/monarch-sharing-shortcode.php:48

Stack trace:
#0 /wp-content/plugins/monarch-sharing-shortcode-master/monarch-sharing-shortcode.php(26): MSS\\\\generate_inline_icons('et_social_inlin...', '', false)
#1 /wp-includes/shortcodes.php(319): MSS\\\\monarch_sharing_shortcode(Array, '', 'monarch_share')
#2 [internal function]: do_shortcode_tag(Array)
#3 /wp-includes/shortcodes.php(197): preg_replace_callback('/\\\\\\\\[(\\\\\\\\[?)(monarc...', 'do_shortcode_ta...', '<pre><code>[mon...')
#4 /wp-includes/class-wp-hook.php(288): do_shortcode('<pre><code>[mon...')
#5 /wp-includes/plugin.php(203): WP_Hook->apply_filters('<pre><code>[mon...', Array)
#6 /wp-content/plugins/monarch-sharing-shortcode-master/monarch-sharing-shortcode.php on line 48, referer: ...
```

I have the monarch plugin installed.
The widget is added to a WP Job Manager job listing page.

**Comment by mmirus** [comment] 2018-10-08 13:59
Hi @rejhgadellaa - thanks for reporting. What version of Monarch do you have? I may need to update my plugin to work with recent changes in Monarch.

**Comment by mmirus** [comment] 2018-10-08 14:48
Hi @rejhgadellaa - can you confirm that you have the Monarch plugin (not just Monarch Sharing Shortcode) activated? The only way I could reproduce this error was by deactivating Monarch.

**Comment by rejhgadellaa** [comment] 2018-10-08 15:29
Yes I have it activated. We're running the latest version of Monarch.

But now that I think of it.. we're running it in multi-site mode (long story, not by our choice ;)) and that has caused some weird issues in the past with other plugins. Maybe that's the problem?

**Comment by mmirus** [comment] 2018-10-08 16:52
That's possible - I haven't tested it on a multisite network. I would have expected it to work if both Monarch and this plugin are activated on the specific subsite you're testing on, but sometimes weird issues pop up, like you said.

**Comment by mmirus** [comment] 2018-10-09 21:57
Closing this since I'm unable to reproduce. More than happy to reopen and troubleshoot (or accept fixes) if you're able to provide additional info.

**Closed as completed by mmirus** 2018-10-09 21:57 UTC
